// Spec section 8. Reuses lib/recommendations/recommendation-engine.ts and
// lib/backend/product-service.ts's listActiveRecommendationProducts
// unchanged — that query already excludes archived/inactive products and
// factors skin-type, severity, and priority, so nothing about ranking
// changes here, only presentation. "Match Score" is shown as the existing
// matchStrength tier (Primary/Supporting/Optional), not the raw numeric
// `score` field, to stay consistent with the no-invented-precision decision.
import Image from "next/image"
import { IconExternalLink } from "@tabler/icons-react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip"
import type { IngredientDetail } from "@/lib/recommendations/types"
import type { ReportViewModel } from "@/lib/reports/report-view-model"

const MATCH_LABEL: Record<string, string> = {
  primary: "Primary match",
  supporting: "Supporting match",
  optional: "Optional match",
}

export function RecommendedProducts({ vm }: { vm: ReportViewModel }) {
  return (
    <Card className="print:break-inside-avoid">
      <CardHeader>
        <CardTitle>Recommended Aurora Organics Products</CardTitle>
        <CardDescription>Matched from the live Aurora Organics product catalog — never generated by the AI.</CardDescription>
      </CardHeader>
      <CardContent>
        {vm.recommendations.length === 0 ? (
          <p className="text-sm text-muted-foreground">
            No matching Aurora Organics products are currently available for this recommendation.
          </p>
        ) : (
          <div className="grid gap-4 md:grid-cols-3">
            {vm.recommendations.map((match) => (
              <div
                key={match.product.id}
                className="flex flex-col gap-3 rounded-xl border border-border p-4 print:break-inside-avoid"
              >
                <div className="relative aspect-square overflow-hidden rounded-lg bg-muted">
                  {match.product.imagePath ? (
                    <Image
                      src={match.product.imagePath}
                      alt={match.product.name}
                      fill
                      sizes="200px"
                      className="object-cover"
                    />
                  ) : null}
                </div>

                <div className="space-y-1">
                  <p className="font-medium text-foreground">{match.product.name}</p>
                  <p className="text-xs text-muted-foreground uppercase tracking-wide">{match.product.category}</p>
                </div>

                <Badge variant={match.matchStrength === "primary" ? "secondary" : "outline"} className="w-fit">
                  {MATCH_LABEL[match.matchStrength] ?? match.matchStrength}
                </Badge>

                <p className="text-sm text-muted-foreground">{match.product.shortDescription}</p>

                {match.reasons.length > 0 ? (
                  <p className="text-xs text-muted-foreground">
                    <span className="font-medium text-foreground">Why it was selected: </span>
                    {match.reasons.join(" ")}
                  </p>
                ) : null}

                <IngredientChips ingredients={match.product.ingredientDetails} />

                <p className="text-xs text-muted-foreground">
                  <span className="font-medium text-foreground">Recommended usage: </span>
                  Use during the {capitalize(match.routineStep)} step of your routine.
                </p>

                <Badge variant="secondary" className="w-fit">
                  Available
                </Badge>

                {match.product.officialUrl ? (
                  <Button asChild variant="outline" size="sm" className="mt-auto">
                    <a href={match.product.officialUrl} target="_blank" rel="noopener noreferrer">
                      Purchase
                      <IconExternalLink className="size-3.5" />
                    </a>
                  </Button>
                ) : null}
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  )
}

function capitalize(value: string) {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

// Hover/tap a chip for the ingredient's cosmetic role — already resolved
// (name + disclaimer-consistent, non-medical description) against the real
// Ingredient table by lib/backend/product-service.ts's mapProduct. Renders
// nothing when the product has no recognized ingredient (most products in
// this catalog don't — see AGENTS.md's "no fabrication" rule extended
// here), same graceful-omission pattern as the "Why it was selected" block
// above it.
function IngredientChips({ ingredients }: { ingredients: IngredientDetail[] | undefined }) {
  if (!ingredients || ingredients.length === 0) return null

  return (
    <div className="space-y-1.5">
      <p className="text-xs font-medium text-foreground">Key ingredients</p>
      <div className="flex flex-wrap gap-1.5">
        {ingredients.map((ingredient) => (
          <Tooltip key={ingredient.name}>
            <TooltipTrigger asChild>
              <Badge variant="outline" className="cursor-default px-2 py-1 normal-case">
                {ingredient.name}
              </Badge>
            </TooltipTrigger>
            <TooltipContent side="top" className="max-w-56 text-wrap">
              {ingredient.description}
            </TooltipContent>
          </Tooltip>
        ))}
      </div>
    </div>
  )
}
